# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5330146e566c574e0ce93971a01d66c30f7347f92a79b64604c0b1a8af7bff295e30e1c134ab46f4dd162cb5ead316cf2f556e5b5bba6b31bfb186522fcfd254

test:
  secret_key_base: f12ade78ab7a005558948192753b9ea58d39ac892bae9036659871e88384058aaad93c48483d996e3084d22ab6c3ce7486aa79a5daf9ea4b2dec63eb63d21a44

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
